---
apiVersion: v1
kind: Namespace
metadata:
  name: demo
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: go-web-hello-world
  namespace: demo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: go-web-hello-world
    spec:
      containers:
      - name: go-web-hello-world
        image: gitlab.rnd.gic.ericsson.se:4567/raket/demo/go-web-hello-world:rick-0.0.1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: go-web-hello-world
  namespace: demo
  labels:
    app: go-web-hello-world
spec:
  type: NodePort
  ports:
  - port: 80
  selector:
    app: go-web-hello-world
